- name: Install infra-tusd-server
  hosts: infra-tusd-server

  tasks:
    - name: Common | Add US APT Mirrors
      action: template src=templates/sources.list dest=/etc/apt/sources.list
      register: apt_sources

    - name: Common | Update APT
      apt: upgrade=dist cache_valid_time=3600 update_cache=yes dpkg_options='force-confold,force-confdef'
      when: apt_sources|changed

    - name: Common | Install Packages
      apt: pkg={{ item }} state=present
      with_items:
        - apg
        - build-essential
        - curl
        - git-core
        - htop
        - iotop
        - libpcre3
        - logtail
        - mlocate
        - mtr
        - mysql-client
        - psmisc
        - telnet
        - vim
        - wget

    - name: Common | Add convenience shortcut wtf
      action: lineinfile dest=/home/ubuntu/.bashrc line="alias wtf='sudo tail -f /var/log/*{log,err} /var/log/{dmesg,messages,*{,/*}{log,err}}'"
      register: bashrc


  # - name: Tus | Download tusd
  #   action: foo bar
  #   register: foo bar
  #
  # - name: Tus | Install upstart/systemd file
  #   action: foo bar
  #   register: foo bar
  #
  # - name: Tus | Start service
  #   action: foo bar
  #   register: foo bar
