- hosts: infra-tusd-server
  name: Install infra-tusd-server
  tasks:
    - action: template src=templates/sources.list dest=/etc/apt/sources.list
      name: 'Common | Add US APT Mirrors'
      register: apt_sources
    - apt: "upgrade=dist cache_valid_time=3600 update_cache=yes dpkg_options='force-confold,force-confdef'"
      name: 'Common | Update APT'
      when: 'apt_sources|changed'
    - apt: 'pkg={{ item }} state=present'
      name: 'Common | Install Packages'
      with_items:
        - apg
        - build-essential
        - curl
        - git-core
        - htop
        - iotop
        - libpcre3
        - logtail
        - mlocate
        - mtr
        - mysql-client
        - psmisc
        - telnet
        - vim
        - wget
    - action: "lineinfile dest=/home/ubuntu/.bashrc line=\"alias wtf='sudo tail -f /var/log/*{log,err} /var/log/{dmesg,messages,*{,/*}{log,err}}'\""
      name: 'Common | Add convenience shortcut wtf'
    - file: path=/srv/tusd/current state=directory owner=www-data group=www-data mode=0755 recurse=yes
      name: 'tusd | Create approot'
    - action: copy src=templates/tusd dest=/srv/tusd/current/tusd mode=0755
      name: 'tusd | Download binary'
    - file: path=/mnt/tusd-data state=directory owner=www-data group=www-data mode=0755 recurse=yes
      name: 'tusd | Create dataroot'
    - action: template src=templates/env dest=/srv/tusd/current/env.sh mode=0600 owner=root group=root
      name: 'tusd | Upload environment'
    - action: template src=templates/upstart-tusd dest=/etc/init/tusd.conf
      name: 'tusd | Install upstart file'
    - action: service name=tusd state=restarted
      name: 'tusd | Restart'
